### ISSUE TITLE
提交表单失效了

### ISSUE THREAD

**Issue by Postroggy** [Crazyokd/yiban-auto#1]
感觉它这个csrf是随机生成的，但是到zui后提交表单的时候，一直都提示 invaild csrf，说明现在这个随便改一个csrf是有问题的了。前几天还用的好好的，现在估计易班改了，找不到它到底在哪里生成了csrf

**Comment by Crazyokd** [comment]
趁热测试了一下，还能正常打卡啊！
<img width="272" alt="image" src="https://user-images.githubusercontent.com/74645100/169705519-e8365560-9147-4511-8673-d6fd6b5c053e.png">
