### ISSUE TITLE
7月底易班登陆添加了验证码是如何绕过的？

### ISSUE THREAD

**Issue by MOLIzhang** [Crazyokd/yiban-auto#2]

**Comment by Crazyokd** [comment]
通过校本化登录打卡，并没有验证码，只是有时需要认证。

**Comment by Crazyokd** [comment]
参考 [fast-yiban](https://github.com/yige233/fast_yiban) 换了它那个登录接口。具体见 [v4.1.0](https://github.com/Crazyokd/yiban-auto/releases/tag/v4.1.0)

![image](https://user-images.githubusercontent.com/74645100/187849058-e568daa3-1ae7-4f77-88ea-ded7e265b348.png)

**Comment by MOLIzhang** [comment]
> 参考 fast-yiban 换了它那个登录接口。具体见 v4.1.0
> 
> ![image](https://user-images.githubusercontent.com/74645100/187849058-e568daa3-1ae7-4f77-88ea-ded7e265b348.png)

非常感谢！ 因为我校用的不是校本化，但我想应该大同小异。 7月易班更新之后就一直没有找到接入的方法😢

**Comment by Crazyokd** [comment]
> 

无法校本化打卡，也应该能够用这个新的登录接口，曾经有过一次成功案例。
> 不过与校本化打卡不同， cookie 名字没变。

**Comment by MOLIzhang** [comment]
> > 
> 
> 无法校本化打卡，也应该能够用这个新的登录接口，曾经有过一次成功案例。
> 
> > 不过与校本化打卡不同， cookie 名字没变。

就是说logintoken不需要改成yiban_user_token吗

**Comment by Crazyokd** [comment]
> > > 
> > 
> > 
> > 无法校本化打卡，也应该能够用这个新的登录接口，曾经有过一次成功案例。
> > > 不过与校本化打卡不同， cookie 名字没变。
> 
> 就是说logintoken不需要改成yiban_user_token吗

那次就是这样， `_access_token` 获取方式发生了改变（因为改变了登录接口），但是后续使用（比如auth）时， `cookie` 名字仍然为 `loginToken` (auth `url` 也不改变)。两种方式不妨都试下，都不行的话可能得手动抓包了:persevere:。

**Comment by MOLIzhang** [comment]
还是好难 感觉有点被劝退了😞
