### ISSUE TITLE
JSESSIONID有问

### ISSUE THREAD

**Issue by Mfyacn** [Crazyokd/yiban-auto#3]
我们学校的易班打卡是这种结构，易班打开https://f.yiban.cn/iappxxxx后点击打卡外链，我抓包后发现cookies是JSESSIONID，我应该怎么做才能自动打卡

**Comment by Crazyokd** [comment]
> 我们学校的易班打卡是这种结构，易班打开[https://f.yiban.cn/iappxxxx后点击打卡外链，我抓包后发现cookies是JSESSIONID，我应该怎么做才能自动打卡](https://f.yiban.cn/iappxxxx%E5%90%8E%E7%82%B9%E5%87%BB%E6%89%93%E5%8D%A1%E5%A4%96%E9%93%BE%EF%BC%8C%E6%88%91%E6%8A%93%E5%8C%85%E5%90%8E%E5%8F%91%E7%8E%B0cookies%E6%98%AFJSESSIONID%EF%BC%8C%E6%88%91%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%81%9A%E6%89%8D%E8%83%BD%E8%87%AA%E5%8A%A8%E6%89%93%E5%8D%A1)

没明白你意思

**Comment by Mfyacn** [comment]
已经解决了
